@startuml

package zombieSurvival {
    class Juego {
            - ListaHilos zonaComun
            - ListaHilos zonaDescanso
            - ListaHilos comiendo
            - ListaHilos colaComedorTxt
            - Text textoComida
            - ArrayList<ListaHilos> esperaTuneles
            - ArrayList<ListaHilos> tunelesTxt
            - ArrayList<Tunel> tuneles
            - ArrayList<ListaHilos> vueltaTuneles
            - ArrayList<ZonaRiesgoH> riesgoIzq
            - ArrayList<ListaHilos> riesgoDch
            - LinkedBlockingDeque<String> colaComedor
            - ArrayList<CyclicBarrier> barrerasTuneles
            - boolean enPausa
            - boolean infoIn
            - ArrayList<Zombie> zombies
            - Lock cerrojoZ
            + humanosEnTunel(int): Integer
            + humanosEnRiesgo(int): Integer
            + zombiesEnRiesgo(int): Integer
            + zombiesMortales(): ArrayList<String>
            + nuevoZombie(Zombie)
            + pausar()
            + reanudar()
            + esperarSiPausado()
            + cruzarIda(Humano, int)
            + cruzarVuelta(Humano, int)
            + comer(Humano)
            + dejarComida(Humano)
        }
}

@enduml